<a href="https://colab.research.google.com/github/hitarthi45/GENAI/blob/main/GENAI_lab_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install FlagEmbedding

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 947.8/947.8 kB 24.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 34.4 MB/s eta 0:00:00


In [ ]:
from FlagEmbedding import BGEM3FlagModel

model = BGEM3FlagModel('BAAI/bge-m3',
                       use_fp16=True) # Setting use_fp16 to True speeds up computation with a slight performance degradation

sentences_1 = ["What is BGE M3?", "Defination of BM25"]
sentences_2 = ["BGE M3 is an embedding model supporting dense retrieval, lexical matching and multi-vector interaction.",
               "BM25 is a bag-of-words retrieval function that ranks a set of documents based on the query terms appearing in each document"]

embeddings_1 = model.encode(sentences_1,
                            batch_size=12,
                            max_length=8192, # If you don't need such a long length, you can set a smaller value to speed up the encoding process.
                            )['dense_vecs']
embeddings_2 = model.encode(sentences_2)['dense_vecs']
similarity = embeddings_1 @ embeddings_2.T
print(similarity)
# [[0.6265, 0.3477], [0.3499, 0.678 ]]


Reconstructing (incomplete total...): |          |  0.00B /  0.00B            

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[[0.6259035  0.3474958 ]
 [0.34986812 0.6782463 ]]


In [ ]:
from FlagEmbedding import BGEM3FlagModel

model = BGEM3FlagModel('BAAI/bge-m3',
                       use_fp16=True)

Reconstructing (incomplete total...): |          |  0.00B /  0.00B            

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

In [ ]:
sentences_1 = ["I LOVE GENAI"]
embeddings_1 = model.encode(sentences_1,
                            batch_size=12,
                            max_length=8192, # If you don't need such a long length, you can set a smaller value to speed up the encoding process.
                            )['dense_vecs']


In [ ]:
embeddings_1

array([[-0.04204996,  0.0040168 , -0.01458733, ..., -0.02487984,
        -0.04212679,  0.03624649]], dtype=float32)

In [ ]:
sentences_2 = ["I LOVE GENAI"]
embeddings_2 = model.encode(sentences_2,
                            batch_size=12,
                            max_length=8192, # If you don't need such a long length, you can set a smaller value to speed up the encoding process.
                            )['dense_vecs']

In [ ]:
embeddings_2

array([[-0.04204996,  0.0040168 , -0.01458733, ..., -0.02487984,
        -0.04212679,  0.03624649]], dtype=float32)

In [ ]:
import numpy as np

#cosine similarity

similarity = np.dot(embeddings_1[0], embeddings_2[0]) / (np.linalg.norm(embeddings_1[0]) * np.linalg.norm(embeddings_2[0]))

In [ ]:
similarity

np.float32(1.0)

In [ ]:
#RECOMMENDATION SYSTEM MOVIES : BASED GENRE


movies = [
    {
        "title": "Inception",
        "genre": "Sci-Fi, Thriller",
        "description": "A skilled thief enters people's dreams to steal secrets and attempts to plant an idea in someone's mind."
    },
    {
        "title": "Interstellar",
        "genre": "Sci-Fi, Adventure, Drama",
        "description": "Astronauts travel through a wormhole in space to find a new home for humanity."
    },
    {
        "title": "The Dark Knight",
        "genre": "Action, Crime, Drama",
        "description": "Batman faces a dangerous criminal mastermind who creates chaos and terror across Gotham City."
    },
    {
        "title": "Avengers: Endgame",
        "genre": "Action, Adventure, Sci-Fi",
        "description": "Superheroes reunite to reverse the devastating consequences caused by a powerful villain."
    },
    {
        "title": "Titanic",
        "genre": "Romance, Drama",
        "description": "A young couple from different social backgrounds fall in love during the tragic voyage of the Titanic."
    },
    {
        "title": "The Notebook",
        "genre": "Romance, Drama",
        "description": "Two young people fall deeply in love but face family pressure and separation before finding their way back to each other."
    },
    {
        "title": "The Conjuring",
        "genre": "Horror, Mystery, Thriller",
        "description": "Paranormal investigators help a family experiencing terrifying supernatural events in their new home."
    },
    {
        "title": "It",
        "genre": "Horror, Thriller",
        "description": "A group of children confronts a terrifying supernatural creature that appears in the form of a clown."
    },
    {
        "title": "The Hangover",
        "genre": "Comedy",
        "description": "Friends travel to Las Vegas for a bachelor party and wake up with no memory of what happened the previous night."
    },
    {
        "title": "3 Idiots",
        "genre": "Comedy, Drama",
        "description": "Three engineering students experience friendship, academic pressure, love, and the struggle to follow their dreams."
    },
    {
        "title": "Dangal",
        "genre": "Sports, Drama",
        "description": "A former wrestler trains his daughters to become successful wrestlers despite social and family challenges."
    },
    {
        "title": "The Pursuit of Happyness",
        "genre": "Drama, Biography",
        "description": "A struggling father fights poverty while trying to build a better future for himself and his young son."
    },
    {
        "title": "The Matrix",
        "genre": "Sci-Fi, Action",
        "description": "A computer programmer discovers that reality is a simulated world controlled by intelligent machines."
    },
    {
        "title": "Jurassic Park",
        "genre": "Sci-Fi, Adventure, Thriller",
        "description": "Scientists create a theme park filled with genetically engineered dinosaurs, but the creatures escape and threaten the visitors."
    },
    {
        "title": "Forrest Gump",
        "genre": "Drama, Romance",
        "description": "A kind-hearted man experiences important historical events while navigating friendship, love, and personal challenges."
    }
]




In [ ]:
texts = [
    f"{movie['title']}. Genre: {movie['genre']}. {movie['description']}"
    for movie in movies
]

for text in texts:
    print(text)

Inception. Genre: Sci-Fi, Thriller. A skilled thief enters people's dreams to steal secrets and attempts to plant an idea in someone's mind.
Interstellar. Genre: Sci-Fi, Adventure, Drama. Astronauts travel through a wormhole in space to find a new home for humanity.
The Dark Knight. Genre: Action, Crime, Drama. Batman faces a dangerous criminal mastermind who creates chaos and terror across Gotham City.
Avengers: Endgame. Genre: Action, Adventure, Sci-Fi. Superheroes reunite to reverse the devastating consequences caused by a powerful villain.
Titanic. Genre: Romance, Drama. A young couple from different social backgrounds fall in love during the tragic voyage of the Titanic.
The Notebook. Genre: Romance, Drama. Two young people fall deeply in love but face family pressure and separation before finding their way back to each other.
The Conjuring. Genre: Horror, Mystery, Thriller. Paranormal investigators help a family experiencing terrifying supernatural events in their new home.
It. G

In [ ]:
embedding=[]
for text in texts:

    embeddings= model.encode(text,
                            batch_size=12,
                            max_length=8192, # If you don't need such a long length, you can set a smaller value to speed up the encoding process.
                            )['dense_vecs']
    embedding.append(embeddings)


In [ ]:
len(embedding)

15

In [ ]:
embedding

[array([-0.00202693,  0.0201381 , -0.01109634, ..., -0.05026658,
        -0.02285776, -0.01060469], dtype=float32),
 array([-0.02848639, -0.01454587, -0.01094803, ..., -0.02769613,
        -0.01036233, -0.01382132], dtype=float32),
 array([ 0.02084275, -0.00561649, -0.02002954, ..., -0.00626637,
         0.00443491, -0.00091101], dtype=float32),
 array([ 1.7036576e-02,  6.5596098e-05, -2.2263847e-02, ...,
         9.5007792e-03, -1.9547462e-02, -4.3077352e-03], dtype=float32),
 array([-0.01280117,  0.00654286, -0.02925876, ..., -0.00090848,
        -0.00543806, -0.03208977], dtype=float32),
 array([ 0.0002628 ,  0.02121896, -0.02594645, ..., -0.02374038,
        -0.01331762, -0.02248945], dtype=float32),
 array([-0.0235125 ,  0.00596215, -0.05109383, ..., -0.03574776,
        -0.01066542,  0.00150537], dtype=float32),
 array([ 0.00691109,  0.03665004, -0.01400833, ..., -0.02990024,
        -0.0122845 , -0.00668951], dtype=float32),
 array([ 0.01174693,  0.01989347, -0.01785168, ...,  0

In [ ]:
query="I want to watch space movie"

In [ ]:
embeddings_Q= model.encode(query,
                        batch_size=12,
                        max_length=8192, # If you don't need such a long length, you can set a smaller value to speed up the encoding process.
                        )['dense_vecs']

In [ ]:
embeddings_Q

array([-0.02240945,  0.02309795, -0.04404929, ..., -0.06079755,
       -0.03096655,  0.051058  ], dtype=float32)

In [ ]:
for i in embedding:
  similarity_score=np.dot(i, embeddings_Q) / (np.linalg.norm(i) * np.linalg.norm(embeddings_Q))
  print(similarity_score)

0.51576585
0.56447333
0.43669143
0.465387
0.48650634
0.44124305
0.44692978
0.44884613
0.45476976
0.44492936
0.41971424
0.43065858
0.48531336
0.45900872
0.44435847


In [ ]:
#print movie names as well with matching score in descending order

#howework !!!!
